 const data=[{"Name":"Banana, Fresh","Protein":1.1,"Net Carbs":20.2,"Fat":0.3,"cal":89},
{"Name":"Chicken Breast, Skin Removed Before Cooking","Protein":30.9,"Net Carbs":0,"Fat":4.5,"cal":173},
{"Name":"Olive Oil","Protein":0,"Net Carbs":0,"Fat":4.5,"cal":40},
{"Name":"Avocado, Black Skin","Protein":2,"Net Carbs":1.8,"Fat":15.4,"cal":167},
{"Name":"Cucumber, Raw, With Peel","Protein":0.7,"Net Carbs":2.4,"Fat":0.1,"cal":15},
{"Name":"Apple, Fresh, With Skin","Protein":0.4,"Net Carbs":15.8,"Fat":0.3,"cal":77},
{"Name":"Tomato Raw, Includes Cherry, Grape, Roma","Protein":0.8,"Net Carbs":2.3,"Fat":0.2,"cal":16},
{"Name":"Baby Spinach, Raw","Protein":2.9,"Net Carbs":1.4,"Fat":0.4,"cal":23},
{"Name":"Oatmeal, Regular or Quick Cooking, Dry","Protein":10.7,"Net Carbs":46.7,"Fat":5.3,"cal":307},
{"Name":"Carrots, Raw","Protein":6.3,"Net Carbs":6.6,"Fat":0.2,"cal":41},
{"Name":"Tap Water","Protein":0,"Net Carbs":0,"Fat":0,"cal":0},
{"Name":"Broccoli, Cooked From Fresh","Protein":16.7,"Net Carbs":3.9,"Fat":0.4,"cal":35},
{"Name":"Chia Seeds","Protein":1.7,"Net Carbs":0.8,"Fat":3.1,"cal":41},
{"Name":"Strawberries, Fresh","Protein":0.7,"Net Carbs":5.5,"Fat":0.3,"cal":323},
{"Name":"Walnuts","Protein":15.2,"Net Carbs":6.8,"Fat":65.2,"cal":654},
{"Name":"Blueberries, Fresh","Protein":1.1,"Net Carbs":17,"Fat":0.5,"cal":84},
{"Name":"Onion, White, Yellow or Red, Raw","Protein":1.2,"Net Carbs":8.5,"Fat":0.1,"cal":44},
{"Name":"Sweet Potato, Baked","Protein":5.4,"Net Carbs":46.3,"Fat":0.4,"cal":241},
{"Name":"Pepper, Sweet, Red, Raw","Protein":1.2,"Net Carbs":4.6,"Fat":0.4,"cal":31},
{"Name":"Coffee, Prepared From Grounds","Protein":0.04,"Net Carbs":0,"Fat":0.1,"cal":4},
{"Name":"Rice, White, Long-Grain, Regular, Enriched, Cooked","Protein":4.3,"Net Carbs":43.9,"Fat":0.4,"cal":205},
{"Name":"Flax Seeds, Not Fortified","Protein":1.3,"Net Carbs":0.1,"Fat":3,"cal":37},
{"Name":"Salmon, Atlantic, Wild, Cooked","Protein":25,"Net Carbs":0,"Fat":8.1,"cal":182},
{"Name":"Mushrooms, Cooked from Fresh","Protein":0.6,"Net Carbs":0.6,"Fat":0.1,"cal":8},
{"Name":"Butter, Unsalted","Protein":0.2,"Net Carbs":0,"Fat":23,"cal":203},
{"Name":"Cheddar Cheese, Natural","Protein":6.5,"Net Carbs":1,"Fat":9.4,"cal":114},
{"Name":"Egg Whites Only, Cooked","Protein":10.9,"Net Carbs":0.7,"Fat":0.2,"cal":52},
{"Name":"Brazil Nuts, Unsalted","Protein":0.7,"Net Carbs":0.2,"Fat":3.2,"cal":31},
{"Name":"Lentils, Boiled","Protein":9,"Net Carbs":14.3,"Fat":0.4,"cal":116},
{"Name":"Peanut Butter, Unsalted","Protein":3.6,"Net Carbs":2.8,"Fat":8.3,"cal":96},
{"Name":"Mushrooms, Raw","Protein":2.2,"Net Carbs":1,"Fat":0.2,"cal":15},
{"Name":"Courgette, Raw","Protein":2.4,"Net Carbs":4,"Fat":0.6,"cal":33},
{"Name":"Broccoli, Cooked from Frozen","Protein":3.1,"Net Carbs":2.3,"Fat":0.1,"cal":28},
{"Name":"Grape, Red or Green (European Type, such as Thompson Seedless), Adherent Skin, Raw","Protein":0.7,"Net Carbs":17.1,"Fat":0.2,"cal":69},
{"Name":"Almonds, Raw","Protein":21.2,"Net Carbs":8.8,"Fat":49.9,"cal":579},
{"Name":"Sunflower Seeds, Raw","Protein":20.8,"Net Carbs":11.4,"Fat":51.5,"cal":584},
{"Name":"Raw Egg","Protein":6.3,"Net Carbs":0.6,"Fat":5.3,"cal":78},
{"Name":"Potato, Boiled with Skin","Protein":1.6,"Net Carbs":15.5,"Fat":0.1,"cal":76},
{"Name":"Lettuce, Romaine or Cos","Protein":0.1,"Net Carbs":0.1,"Fat":0,"cal":1},
{"Name":"Honey","Protein":0.1,"Net Carbs":17.3,"Fat":0,"cal":64},
{"Name":"Coconut Oil","Protein":0,"Net Carbs":0,"Fat":13.5,"cal":122},
{"Name":"Blueberries, Frozen, Unsweetened","Protein":0.4,"Net Carbs":9.5,"Fat":0.6,"cal":51},
{"Name":"Milk, Whole","Protein":0.9,"Net Carbs":1.4,"Fat":0.9,"cal":17},
{"Name":"Brown Rice, Cooked in Unsalted Water","Protein":0.8,"Net Carbs":6.8,"Fat":0.3,"cal":35},
{"Name":"Baby Kale, Raw","Protein":0.6,"Net Carbs":0,"Fat":0.3,"cal":7},
{"Name":"Egg, Whole, Cooked, Hard-Boiled","Protein":6.3,"Net Carbs":0.6,"Fat":5.3,"cal":78}]


export default data